Fix build date and revision

diff --git a/.github/workflows/multiarch-build.yaml b/.github/workflows/multiarch-build.yaml
--- a/.github/workflows/multiarch-build.yaml
+++ b/.github/workflows/multiarch-build.yaml
@@ -61,13 +61,37 @@ jobs:
         id: release-version
         run: |
           set -e
-          PACKAGE_VERSION=$(grep -i "ENV ${{ inputs.image }}_VERSION" ${{ inputs.dockerfile }} | cut -d "=" -f 2 | sed 's/"//g')
-          if [ -z "$PACKAGE_VERSION" ]; then
+          RELEASE_VERSION=$(grep -i "ENV ${{ inputs.image }}_VERSION" ${{ inputs.dockerfile }} | cut -d "=" -f 2 | sed 's/"//g')
+          if [ -z "$RELEASE_VERSION" ]; then
             echo "Error: Unable to extract package version from Dockerfile."
             exit 1
           fi
-          echo "release-version=${PACKAGE_VERSION}" >> $GITHUB_ENV
-          echo "Successfully extracted version: $PACKAGE_VERSION"
+          echo "release-version=${RELEASE_VERSION}" >> $GITHUB_ENV
+          echo "Successfully extracted version: $RELEASE_VERSION"
+
+      - name: Set build date
+        id: build-date
+        run: |
+          set -e
+          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
+          if [ -z "$BUILD_DATE" ]; then
+            echo "Error: Unable to set build date."
+            exit 1
+          fi
+          echo "build-date=${BUILD_DATE}" >> $GITHUB_ENV
+          echo "Successfully set build date: $BUILD_DATE"
+
+      - name: Set revision
+        id: revision
+        run: |
+          set -e
+          REVISION=$(git rev-parse HEAD)
+          if [ -z "$REVISION" ]; then
+            echo "Error: Unable to set revision."
+            exit 1
+          fi
+          echo "revision=${REVISION}" >> $GITHUB_ENV
+          echo "Successfully set revision: $REVISION"
 
       - name: Build and push
         uses: docker/build-push-action@v5
@@ -76,8 +100,8 @@ jobs:
           file: ${{ inputs.dockerfile }}
           platforms: linux/amd64,linux/arm64
           build-args: |
-            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
-            REVISION=$(git rev-parse HEAD)
+            BUILD_DATE=${{ env.build-date }}
+            REVISION=${{ env.revision }}
           tags: |
             ${{ inputs.username }}/${{ inputs.image }}:${{ env.release-version }}
             ${{ inputs.username }}/${{ inputs.image }}:latest
